### ISSUE TITLE
Memory/connection problems

### ISSUE THREAD

**Issue by FabioQ** [ifsnop/mysqldump-php#100]
I'm investigating some sort of bug in the behavior of mysqldump, after using it in a VM, mapped on a routed api, after 2 or 3 days of usage, suddenly everything stop working, there is a weird high memory usage on machine and after mysqldump->start it don't write on disk at all,
No error messages. I don't know actually why this is happening, probably it full some buffer,socket or memory somewhere.
This is the "ps aux --sort -rss" result
`mysql    32344  0.0 24.0 1152460 460576 pts/2  Sl   10:39   0:02 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --user=mysql --log-error=/var/log/mysqld.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/lib/mysql/mysql.sock`

Even restarting mysql it won't help, 2 minutes of using it and it's back on this resources

**Comment by ifsnop** [comment]
Could you please try this fix? If this doesn't work, could you try clearing the Mysqldump-php object?

**Comment by phpony** [comment]
You should tune your MySQL setup. Freeing dbhandler on destroy will change nothing cause this dumper is not a daemon - everything will be freed when the job is done.

Try something like:
https://github.com/major/MySQLTuner-perl

Or read about tuning MySQL for small memory VMs. 

Also you can connect to MySQL console before starting backup and execute "SHOW PROCESSLIST;" when it stuck to examine which query took all the resources. It probably will be "SELECT" everything from some large table with a lot of indexes.

**Comment by ifsnop** [comment]
mysqldump-php is opening the pdo connection with "PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false
", so php doesn't buffer all the query. Instead, it retrieves small batches from mysql server. The memory footprint of  mysqldump-php is as low as it can be.

I understood from the OP that after several days of running some process, memory is not returned. Of course normal usage will destroy the connection, but if a program is reusing the Mysqldump-php object, it could leak memory.

I don't know what benefit MySQLTuner-perl could do. 

Mysqldump-php has been tried with databases of several GBs under severe low memory conditions.
