### ISSUE TITLE
gzip export file password protection

### ISSUE THREAD

**Issue by canerkoroglu** [ifsnop/mysqldump-php#102]
Hello, first of all thank you very much deploy this plugin,
i wonder is there a way to set password protection to exported gzip files ('compress' => IMysqldump\Mysqldump::GZIP,) ?

**Comment by ifsnop** [comment]
Currently, there is no way to do that. If you want to protect any file, I
would recommend to use gpg https://www.gnupg.org/gph/en/manual/x110.html

On Fri, May 6, 2016 at 4:51 PM, canerkoroglu <notifications@github.com>
wrote:

> Hello, first of all thank you very much deploy this plugin,
> i wonder is there a way to set password protection to exported gzip files
> ('compress' => IMysqldump\Mysqldump::GZIP,) ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/102>
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain
