### ISSUE TITLE
Id's with 0 are changed to 1 

### ISSUE THREAD

**Issue by mag-extension** [ifsnop/mysqldump-php#104]
Hello,

love your script but when I use it with magento and do a dump he changes some id's from 0 to 1. 
After importing it will give issues. I already tried locks table and add locks to false but doesn't help.

Any idea how I can fix this?

**Comment by ifsnop** [comment]
Can you share a small example, so I can try to reproduce the problem?

Thanks.

On Tue, May 24, 2016 at 6:06 PM, mag-extension <notifications@github.com>
wrote:

> Hello,
>
> love your script but when I use it with magento and do a dump he changes
> some id's from 0 to 1.
> After importing it will give issues. I already tried locks table and add
> locks to false but doesn't help.
>
> Any idea how I can fix this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/104>
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain
