### ISSUE TITLE
Constructor Properties

### ISSUE THREAD

**Issue by crossan007** [ifsnop/mysqldump-php#111]
It'd be nice if there was a constructor available that can use an existing PDO connection reference, rather than requiring a DSN / username / password to create a new PDO connection.

**Comment by ifsnop** [comment]
If mysqldump-php reuses a connection, I have always believed that it won't be able to setup the connection as it needs to ensure a consistent output (for example, if PDO inside of a transaction).

What do you think?

**Comment by ifsnop** [comment]
I will be closing this issue because there is not a way to ensure the database is in a consistent state before the dump if the pdo connection is reused.
