### ISSUE TITLE
Save Foreign Key Constraints

### ISSUE THREAD

**Issue by dloewen** [ifsnop/mysqldump-php#112]
Is it possible to export foreign key constraints? Without this some databases can't be wiped and re-inserted without losing that feature.

Example:

```
ALTER TABLE `table1`
  ADD CONSTRAINT `constraint name` FOREIGN KEY (`column1`) REFERENCES `table2` (`column2`) ON DELETE CASCADE ON UPDATE CASCADE;
```

**Comment by ifsnop** [comment]
Actually, mysqldump-php exports foreign key constrains. Could you please provide a simple test case?

Thanks in advance.

**Comment by dloewen** [comment]
Gladly, here's an isolated test case. 

[mysqldump-php-fk-test.zip](https://github.com/ifsnop/mysqldump-php/files/674704/mysqldump-php-fk-test.zip)

Testing procedure:

1. Un-zip, set up a database and import pma-db-export.sql
2. Enter your db connection info in the test.php config array
3. Run test.php

My results are seen in the existing mysqldump-export.sql file. Note that the constraint is missing from that file.

**Comment by ifsnop** [comment]
I have just added a check in https://github.com/ifsnop/mysqldump-php/commit/5520ace72245e3f9c2afe3aa0978b2cadc8b3ea9 to test the dump of the foreign keys, and wasn't able to find the problem. Just read your post and realize that there is no problem!
