### ISSUE TITLE
Formated INSERT INTO

### ISSUE THREAD

**Issue by arxeiss** [ifsnop/mysqldump-php#113]
Hello,

thanks for your great script, it works as a charm.
But sometimes I'm checking queries manually, and then there is problem, that INSERT INTO is in 1 row.
It is nice in Adminer, that INSERT INTO in export produce each record in a separate row, like this

```
INSERT INTO `table` VALUES(a, b, c),
(a, b, c),
(a, b, c),
...
```

I know, that mysqldump utility does not provide a option for this and I will understand if you will say, that you will not put this option into your code. But it would be nice.

**Comment by ifsnop** [comment]
The easiest way to get an output similar to what you ask, is to use extended-inserts=false:

~~~
INSERT INTO `test002` VALUES (1,NULL);
INSERT INTO `test002` VALUES (2,-128);
INSERT INTO `test002` VALUES (3,0);
INSERT INTO `test002` VALUES (4,127);
~~~

Using this syntax will also get you the line error.
