### ISSUE TITLE
reset auto_increment

### ISSUE THREAD

**Issue by oudirichi** [ifsnop/mysqldump-php#114]
It's my first issues I do and i'm not quit sure if it's like this I should do it but I appreciate the lib you did! Sorry if my english is not super good ^^

it would be nice if the mysqldump can reset auto_increment with an option (reset_auto_increment=true/false). 

Why? Sometime we only want the structure to recreate the database without the data and add some seed after.

it could be something easy as: 
```
$file_contents = file_get_contents($path_to_file);
$match = "/AUTO_INCREMENT=[0-9]+/s";
$replace = "AUTO_INCREMENT=1";
$file_contents = preg_replace($match, $replace, $file_contents);
file_put_contents($path_to_file, $file_contents);
```

**Comment by soulseekah** [comment]
Are you depending on IDs to start from 0 in your seeds? If so, why?

If you dump with:

```
	'add-drop-table' => true,
	'no-data' => true,
```

You'll reset any current data and get the structure. Sure the increments will start from a different offset, but it should never be a problem. You shouldn't even be depending on auto increments being sequential, since in some cases it won't be (for example: http://stackoverflow.com/questions/15881400/mysql-autoincrement-is-not-sequential-in-innodb).

Also, `file_get_contents` is definitely not the way to go, would take up too much memory. If you're going to do this do it in `create_table` in a custom Adapter.

**Comment by oudirichi** [comment]
Yeah, this is what I did to get the structure only and I reset the IDs with the solution I give. The reason is I want to export the database structure to default (this way the seeds will always be at the same IDs to work with a team). Like rails did (rake db:schema:dump). 

You right for the memory leak. This is only a fast solution that's worked for me. A better solution would be read line by line and put the result on a new one. 

http://stackoverflow.com/a/236082

**Comment by ifsnop** [comment]
I find this option useful, but also think that the implementation could be
improved. A better place to modify the autonumeric could be inside the
create_table function, when it is firstly defined. If you provide this PR I
will gladly accept it.

--
-- Madrid / Spain

**Comment by soulseekah** [comment]
PR #115 has implementation and tests. Builds passing. Enjoy.

**Comment by ifsnop** [comment]
(just a question) Does it make sense to link the reset_auto_increment with the nodata option? If we have to protect users from their errors, maybe is better to force nodata when using reset?

**Comment by soulseekah** [comment]
One does not work without the other. You need both --no-data and --reset-auto-increment for it to work. Using just --reset-auto-increment will not reset it, since that would product a bad dump. We could output a warning if using --reset-auto-increment without --no-data, telling the user that it has no effect without --no-data.

**Comment by ifsnop** [comment]
Maybe reset_auto_increment should set no_data?

--
-- Madrid / Spain

**Comment by soulseekah** [comment]
Such coupling will probably lead to more confusion, and is unexpected. What if you stupidly set:

```
"no-data" => false,
"reset-auto-increment" => true
```

What do you do? Enable no-data and risk the user not looking and importing the produced file into a live database destroying all data? Or not reset-auto-increment and risk destroying equally stupid expectations that the increment will be reset?

I think such implicit assumptions have no strong argument for coupling the two options.

But you're the maintainer - it's up to you. I just used your tool to save my ass last Tuesday, and decided to thank you by giving back to the project in the form of a random PR to a random issue. So I don't have the deep insight you do. Do what's best :+1: and thanks for the amazing script.

**Comment by ifsnop** [comment]
I was asking about what would be the best way to enable the option, since
I'm not 100% sure. I will have to think about it. Of course I don't want to
risk any user data, but also don't like aborting execution. As you see,
opinions are also very welcomed!

--
-- Madrid / Spain

**Comment by phpony** [comment]
There is an easy solution to this whole problem: "reset-auto-increment" should not force the `AUTO_INCREMENT=1` value, but should simply remove all AUTO_INCREMENT statements from dump. If there will be some data, MySQL will handle this situation and assign proper AUTO_INCREMENT value automatically. If there will be no data - in default environment the `1` will become the AUTO_INCREMENT value without specifying this.

Proposed replacement in related commit:
```
            $match = "/AUTO_INCREMENT=[0-9]+/s";
            $replace = "";
```

There are some special cases like having NO_AUTO_VALUE_ON_ZERO enabled, but if someone will go for "reset-auto-increment" option - we can assume that this person understands what is he doing.

**Comment by oudirichi** [comment]
or maybe multiple options?
```
'reset-auto-increment' => Mysqldump::StartAtOne
'reset-auto-increment' => Mysqldump::None (equivalent to true)
```

**Comment by ifsnop** [comment]
For me the @phpony solution solves all the questions stated in this issue. If nobody disagrees, I will implement his idea.

**Comment by oudirichi** [comment]
if it's reset auto increment i'm fine with this solution ^^
