### ISSUE TITLE
How to use WHERE option for more than one tables?

### ISSUE THREAD

**Issue by GumptionTechnologies** [ifsnop/mysqldump-php#118]
Hello Team,

Thanks for provide such a great tool. I am using it for my POS solution to synch databases between the different systems. This is working great.

I have come across a situation where I need to PULL only data from some table without table structure. I am using 'no-create-info'=>true. But now an interesting scenario has occurred. I need to pull data from these 6 tables using WHERE option. From the documentation, I can see you are using "WHERE" option but I am not sure how to use it for more than one tables in one go.

Looking forward to a quick response on this. 

Regards
Umar

**Comment by ifsnop** [comment]
The "where" option is added for every dump of every table. It enables some fine-grained control over what data is going to be dumped, but was created to target only one table. If there is need for several different where clausules (one for each table), then more than one call to start should be made (one for each table)

**Comment by GumptionTechnologies** [comment]
Can you give an example of how to use the WHERE clause?

**Comment by GumptionTechnologies** [comment]
Alright. I got it working with single table. I am trying to explore your code to do it with multiple table and an independent WHERE clause for each table. :)

I will post back to you.
