### ISSUE TITLE
Auto/Force Download

### ISSUE THREAD

**Issue by bdalina54** [ifsnop/mysqldump-php#120]
Is there an auto or force download feature after backup, without saving the file in the server but directly to the client computer.

**Comment by ifsnop** [comment]
Just take a look at this example:
~~~
https://github.com/ifsnop/mysqldump-php/wiki/Redirecting-to-stdout 
~~~

Before calling start(), set headers to initiate a client download:
~~~
http://php.net/manual/es/function.header.php#86554
~~~

If you want, you could add a working example to the wiki.

**Comment by ve3** [comment]
This example can't do anything. Maybe incomplete or something missing?

```
include_once(dirname(__FILE__) . '/mysqldump-php/src/Ifsnop/Mysqldump/Mysqldump.php');
$dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password');
$dump->start('php://stdout');
```
