### ISSUE TITLE
MYSQL timeout with bigger databases

### ISSUE THREAD

**Issue by djspacedevil** [ifsnop/mysqldump-php#122]
Hy,

can i change this script so, that the max_execution_time and/or timeout is increase in the time of the backup and set back to default or old value when the script is finished?

**Comment by djspacedevil** [comment]
Hy thanks, good tipp. ;)

I i change this in php, but i become after 120 min a query timeout from sql server "mysql server has gone away". it must be the max_execution_time or wait_timeout?
i dont can change this for the hole site.  is it possible to build it in the select? or in PDO before the real request starts?

Best Regards

**Comment by danitxo** [comment]
I think that the problem is on MySQL config side.

Try increasing max_allowed_packet value.

In my.cnf file:
`[mysqld]`
`max_allowed_packet=100M`

Or in memory (will remain until you restart it):
`set global max_allowed_packet=104857600`
