### ISSUE TITLE
Import database?

### ISSUE THREAD

**Issue by madmanmax** [ifsnop/mysqldump-php#123]
Hey there, 

Nice work, I just have one question: Is there also an import counterpart for this library?

Regards,
Max

**Comment by phpony** [comment]
Well, all you need is just read file line by line and pass the strings to MySQL. This is a very easy task that can be solved in 5-6 lines of code. 

You can check some examples here: https://stackoverflow.com/questions/19751354/how-to-import-sql-file-in-mysql-database-using-php

**Comment by ifsnop** [comment]
Maybe we should include this link on the mysqldump-php wiki, just for
future reference.

**Comment by ifsnop** [comment]
https://github.com/ifsnop/mysqldump-php/wiki/Importing-dump-from-php
