### ISSUE TITLE
Backup of Views includes DEFINER Clause

### ISSUE THREAD

**Issue by crossan007** [ifsnop/mysqldump-php#126]
Backup of database views currently includes the ```DEFINER``` clause.

Including this clause causes issues when restoring the dump onto another system with potentially different users.

Restore side workarounds are able to mitigate the issue by string replacing the DEFINER clause with whitespace.

https://bugs.mysql.com/bug.php?id=24680
https://stackoverflow.com/questions/9446783/remove-definer-clause-from-mysql-dumps
https://github.com/ChurchCRM/CRM/issues/3856

**Comment by ifsnop** [comment]
Looks like best solution is to implement a new option as mysqldump did:

http://dev.mysql.com/doc/refman/5.7/en/mysqlpump.html#option_mysqlpump_skip-definer

**Comment by ifsnop** [comment]
I believe the --skip-definer should be enabled by default. What do you think?

**Comment by crossan007** [comment]
I'm inclined to say "yes enabled by default;" however, I'm also questioning "to what extend does the functionality of mysqldump-php match the official mysqldump?"  Would a deviation in default behavior catch any users by surprise?

My limited knowledge / use of ```DEFINER``` and the associated view security context precludes me from providing an objective decision on the matter.

**Comment by ifsnop** [comment]
I have made skip-definer disabled by default by the moment, so not to break existing functionality.

Thanks for your feedback!
