### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by AlexanderBech** [ifsnop/mysqldump-php#133]
Any idea why I am getting this error?:
mysqldump-php error: Connection to mysql failed with message: SQLSTATE[HY000] [2002] Permission denied

**Comment by AlexanderBech** [comment]
I have a connection to the db.

**Comment by ifsnop** [comment]
Hi,

You need to create a new connection, since mysqldump-php needs to setup
some connection parameters by his own. An already created connection could
be in am unknown state, and that may generate some problems.

**Comment by AlexanderBech** [comment]
I fixed it by changing "localhost" to "127.0.0.1".
It gives me permission denied when using "localhost" - i don't know why.

**Comment by ifsnop** [comment]
Look in the mysql.user table. Probably localhost is missing from the user
row.

--
-- Madrid / Spain
