### ISSUE TITLE
Allow setting a closure for the hookTransformColumnValue()

### ISSUE THREAD

**Issue by SjorsO** [ifsnop/mysqldump-php#144]
Currently, the only way to implement a transform column value hook is by extending the Mysqldump class and overriding the `hookTransformColumnValue()` method. It would be nice if we didn't have to extend the class and do the following instead:

```php
$dumper = new IMysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password');

$dumper->setTransformColumnValueHook(function ($tableName, $colName, $colValue) {
    return strtoupper($colValue);
});

$dumper->start('storage/work/dump.sql');
```

Is this something you'd accept a PR for?

**Comment by ifsnop** [comment]
> Currently, the only way to implement a transform column value hook is by
> extending the Mysqldump class and overriding the
> hookTransformColumnValue() method. It would be nice if we didn't have to
> extend the class and do the following instead:
>
> $dumper = new IMysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password');$dumper->setTransformColumnValueHook(function ($tableName, $colName, $colValue) {    return strtoupper($colValue);});$dumper->start('storage/work/dump.sql');
>
> Is this something you'd accept a PR for?
>

I usually don't like the burden DI imposes, but this time it maybe be
cleaner than extending. I would like to see the PR.

Thanks in advance.

>

**Comment by AlchemyUnited** [comment]
"I usually don't like the burden DI imposes, but this time it maybe be cleaner than extending."

It's not a burden if it's the right thing to do :)

BTW, while we're on the subject, how about passing in the whole row with the colValue? That is, if the new value has rules based on other col / values in the row, it would be helpful to know those other values. 

Fringe use case? Perhaps. But my sense is, once you get to wanting to use this hook, it's likely you're wanting / needing something special anyway. So why not just be as open to those possibilities as possible?

**Comment by ifsnop** [comment]
> "I usually don't like the burden DI imposes, but this time it maybe be
> cleaner than extending."
>
> It's not a burden if it's the right thing to do :)
>
> BTW, while we're on the subject, how about passing in the whole row with
> the colValue? That is, if the new value has rules based on other col /
> values in the row, it would be helpful to know those other values.
>
> Fringe use case? Perhaps. But my sense is, once you get to wanting to use
> this hook, it's likely you're wanting / needing something special anyway.
> So why not just be as open to those possibilities as possible?
>

As I see it, the caller should get each value plus the column definition.
Then, for example, you could also change the column type (hashing a
numerical id).

I have thought about this use case, but then column integrity, views, etc
could fail. Maybe mysqldump is not the right place to do this.

>

**Comment by AlchemyUnited** [comment]
re: " the column definition."

I guess it can't hurt but I would presume that __if__you're in deep enough to use the filter you'd (likely) be well enough aware of what you're up to. 

That said, this is where I would like to have more control, in a less hacky sorta way. For example, I'm likely to use this by giving each table dump it's own file. Why? Because on import I'll be able to watch / babysit easier. I don't want table to bomb everything are it. 

I think the other values in the row would be useful more often than not.
