### ISSUE TITLE
Using dependency injection for hookTransformColumnValue()

### ISSUE THREAD

**Issue by AlchemyUnited** [ifsnop/mysqldump-php#145]
I think it's great this hook exists. Thank you!

But it seems to me it would be best handled via dependency injection; using inheritance to take advantage of this hook / method doesn't feel quite right. DI would be less coupled, yes?

**Comment by ifsnop** [comment]
> I think it's great this hook exists. Thank you!
>
> But it seems to me it would be best handled via dependency injection;
> using inheritance to take advantage of this hook / method doesn't feel
> quite right. DI would be less coupled, yes?
>

What do you think of #144?

>

**Comment by AlchemyUnited** [comment]
That would work but but it's really just DI-lite in a way. 

As I got to working with this yesterday the whole felt (read: first impression) what this could benefit from being decomposed / decoupled. While I understand it's intended to be a one-for-one (so to speak) replacement for mysqldump, I'd like to see things broken down / apart and then use a facade (?) to wrap them back together. 

The point being, in it's current form, there's not much flexibility (which is how the normal myselqdump thinks). For example, I'd like to have the natural ability to get a table at a time and write it to it's own dump.sql file. But as it is, I have to accept the whole process end to end, as is. 

Mind you, I can rig up something with include-table / exclude-table, but that feels hack-y to me. I'd like to say "get me Table X"..."Set / load it somewhere else..."..."Now process that..."

Listen. I'm not complaining. This code is going to save me a lot of time (for a one-off-y need). THANK YOU!! But if I was going to use it ongoing I'd likely tear it down and refactor it into small chunks (read: classes).

**Comment by bomoko** [comment]
For what it's worth, I'd be very excited to see this kind of loosely coupled refactoring. Having been working with mysqldump-php for a few months now in the context of gdpr, there are several places where this kind of approach would have made things far cleaner. Happy to help if needed.

**Comment by AlchemyUnited** [comment]
@bomoko - What comes to mind for you? That is, what would your suggestions / "feature requests" be?

Me? In general, I'd like to see more but smaller / focused classes. I'd also like to see methods with wrappers. For example, something like getDatabaseStructureTables() and getDatabaseStructureViews() are more or less identical. I'd also like to see the resulting $this->some_array have a getter. 

Things like that. The pieces are there. But they don't allow for much flexibility if you have a slightly different need. I feel the What & How should be separated from the When (i.e., process that pulls everything together into a typical use).

**Comment by ifsnop** [comment]
getDatabaseStructureTables and getDatabaseStructureViews are different because different sql code has to be used to dump tables and views. Inside them, there is a foreach that iterates through every table or view. I would love to see this simplified, so if you have any actual code, I would like to see it.

**Comment by ifsnop** [comment]
@bomoko I have just accepted #144, hope it makes things easier.
