### ISSUE TITLE
Suggestion: Test / previous option

### ISSUE THREAD

**Issue by AlchemyUnited** [ifsnop/mysqldump-php#146]
Per the other issue (concerning hookTransformColumnValue) I just posted. I should probably explain I intend to use this hook / method to "scrub" sensitive / proprietary data as I dump from production for a local dev DB. 

With that said, it would be helpful to have a test / preview int value that determines how many rows from each table are dumped. This way, if for some reason the scrub didn't go right I've mitigated the exposure to that. For example, better to only have the SSNs for 20 people than say all 2,000+ employees. 

Sure, I can delete that file (with all 2,000 employees) but unless I do something to overwrite my HD  the data itself will still be lurking somewhere.  And of course there's GDPR concerns / implications as well. 

tia i hope this helps.

**Comment by ifsnop** [comment]
With the new hook this should be quite easy. If you write an example we can reference it in the wiki, so other people could benefit.

Thanks in advance.

**Comment by ifsnop** [comment]
I have added the row count in the export file, per table, in the comments section after each table.
