### ISSUE TITLE
 Call to undefined method Ifsnop\Mysqldump\Mysqldump::setTransformColumnValueHook() 

### ISSUE THREAD

**Issue by jima51** [ifsnop/mysqldump-php#156]
i have the error message  "Call to undefined method Ifsnop\Mysqldump\Mysqldump::setTransformColumnValueHook()" when i try the exemple "Changing values when exporting"
But i am in 2.5.0 release ...

**Comment by gmemstr** [comment]
For whatever reason that function didn't make it into the 2.5 release, take a look at [my composer file](https://github.com/gmemstr/database-janitor/blob/master/composer.lock) to pull the latest version from Git directly.

**Comment by jima51** [comment]
I can't use "dev-master" on my production server.
I will wait the next release with this function.
Thanks for your help :)

Do you have any idea when will the next release be released?

**Comment by ifsnop** [comment]
Just let me look at it, I believe that there is an equivalent function
already implemented.

**Comment by ifsnop** [comment]
I can't find the example "Changing values when exporting"... in what branch did you find it?

**Comment by ifsnop** [comment]
Just releasing v2.6 that includes the hook.
