### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY'

### ISSUE THREAD

**Issue by robot110011** [ifsnop/mysqldump-php#160]
Docker PHP-cli 7.3 with PDO installed and working properly.

Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /conqueramazon/src/vendor/ifsnop/mysqldump-php/src/Ifsnop/Mysqldump/Mysqldump.php:176

Any tips to fix this?

**Comment by ifsnop** [comment]
Try this:
https://www.drupal.org/forum/support/installing-drupal/2011-01-06/drupal-7-php-fatal-error-undefined-class-constant-mysql

**Comment by robot110011** [comment]
Will try next week and will report here, thanks for your help!

**Comment by aldavigdis** [comment]
For anyone who ends up here via Google and is running Docker:

The Docker images for PHP don't include the pdo_mysql module and it needs to be added using `docker-php-ext-install pdo_mysql`.

For minimal requirements for most PHP apps such as WordPress, use `docker-php-ext-install -j "$(nproc)" bcmath mysqli zip opcache pdo_mysql`

**Comment by mikemellor11** [comment]
@aldavigdis what does the `-j $(nproc)` do in this example?

**Comment by aldavigdis** [comment]
@mikemellor11: It simply enables threading if you have a multicore CPU, so it makes things go a bit faster.
