### ISSUE TITLE
Missing some functions after composer install this packet

### ISSUE THREAD

**Issue by quang4dev** [ifsnop/mysqldump-php#161]
Hi there, I tried to run composer require ifsnop/mysqldump-php
but the file I get is not the same with your source in this GIT.
please see this file (I must change php to txt to upload it)
[Mysqldump.txt](https://github.com/ifsnop/mysqldump-php/files/3041808/Mysqldump.txt)

Could you pls help me how to solve this?

**Comment by ifsnop** [comment]
Latest stable release was v2.6, you could always follow dev-master to have the current edge version.

However, since long time has passed since last update, I will push v2.7 right now.

**Comment by quang4dev** [comment]
Thanks :)
