### ISSUE TITLE
Export to CSV or excel file

### ISSUE THREAD

**Issue by quang4dev** [ifsnop/mysqldump-php#163]
Could you pls support to export to CSV or microsoft excel types?

**Comment by ifsnop** [comment]
You could export directly to CSV from MySQL using SELECT INTO OUTFILE.

See it here:
https://www.tech-recipes.com/rx/1475/save-mysql-query-results-into-a-text-or-csv-file/

**Comment by courtney-miles** [comment]
> You could export directly to CSV from MySQL using SELECT INTO OUTFILE.

This is only useful if you have access the file system of the server running MySQL -- I.e. it can't write to a remote file system.

For those looking for a solution, perhaps look at [PortPHP](https://portphp.readthedocs.io).

**Comment by ifsnop** [comment]
With the new hooks, you could access columns and implode() them to a
file/web. Maybe this is easier.

You could export directly to CSV from MySQL using SELECT INTO OUTFILE.
>
> This is only useful if you have access the file system of the server
> running MySQL -- I.e. it can't write to a remote file system.
>
