### ISSUE TITLE
--single-transaction Locks database unlike the native mysqldump logic

### ISSUE THREAD

**Issue by andreas-glaser** [ifsnop/mysqldump-php#166]
It appears that `single-transaction` set to `true` does not properly leave InnoDB databases unlocked like `mysqldump` does. 

Here is my config:
```
<?php
// ...
            $dumperMain = new Mysqldump(sprintf('mysql:host=%s;dbname=%s', $this->config['host'], $databaseName),
                $this->config['user'], $this->config['password'], [
                    'single-transaction' => true,
                    'routines' => true,
                    'skip-comments' => true,
                    'skip-definer' => true,
                ]);
// ...
```

**Comment by andreas-glaser** [comment]
Ok found the bug: 

https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_single-transaction
> The --single-transaction option and the --lock-tables option are mutually exclusive because LOCK TABLES causes any pending transactions to be committed implicitly. 

So the code should be changed from 
`if ($this->dumpSettings['lock-tables']) {`
to
`if ($this->dumpSettings['lock-tables'] && !$this->dumpSettings['single-transaction']) {`

**Comment by ifsnop** [comment]
Fixed with https://github.com/ifsnop/mysqldump-php/commit/92bdf13e1343723d473cf92ed629e943f331dbd5
