### ISSUE TITLE
is that's right ? my databse size its 3.3 GB after export it with this library got size 1.69 GB

### ISSUE THREAD

**Issue by medozeus** [ifsnop/mysqldump-php#170]
```
<?php

include "vendor/autoload.php";

use Ifsnop\Mysqldump as IMysqldump;

try {
    $dump = new IMysqldump\Mysqldump('mysql:host=localhost;dbname=ssss', 'ssss', 'sss');
    $dump->start('file/dump.sql');
} catch (\Exception $e) {
    echo 'mysqldump-php error: ' . $e->getMessage();
}
```

**Comment by medozeus** [comment]
the size its 3.3 in phpmyadmin

**Comment by ifsnop** [comment]
Are you referring to the size of the database once it is inserted from the
dump or to the size of the .SQL files?

> the size its 3.3 in phpmyadmin
>

**Comment by medozeus** [comment]
@ifsnop  the size of large table in phpmyadmin give me 3.3 GB after export the database the file with name
dump.sql size its 1.70 GB so did the library export all data ?

**Comment by ifsnop** [comment]
I do lots of testing (manual and automatic) to check for regressions or
bugs when adding new features. For me is ok, but don't trust me, check it.
Just rename the table with phpmyadmin and upload the SQL dump. Then you
could compare original and restored table to see if they have the same
number of columns, rows and data CRC. Beware that this will make your table
unavailable during the test.

Or just load the dump to a new database, and compare.

I could even test it if you don't mind sharing the table.

> @ifsnop <https://github.com/ifsnop> the size of large table in phpmyadmin
> give me 3.3 GB after export the database the file with name
> dump.sql size its 1.70 GB so did the library export all data ?
>

**Comment by medozeus** [comment]
i just made a small test with small database have size 55 MB in phpmyadmin after export the size of .SQL file its 25 MB.
 after that i re import it  by phpmyadmin and  the size its 55 MB in phpmyadmin :D
i dont know why there is different in size reading in phpmyadmin and .SQL file but no data lose in this test
