### ISSUE TITLE
Allowed memory size XXX, or, many tables

### ISSUE THREAD

**Issue by douglasduartetb** [ifsnop/mysqldump-php#172]
Hi, when i backup the database, i have no problem when the table has millions of values, but, when i have many tables, like 10.000++, in another database, i receive this issue. 

For now, i solve increasing de memory_limit in php.ini.

Don't ask me why the database has 10.000 tables, when i get here, the shit was already done.

---
Here :D , looks like is an array in 524 
![Captura de Tela 2019-09-03 às 10 16 02](https://user-images.githubusercontent.com/7443043/64176687-5323ff00-ce34-11e9-9a1c-126bdb519778.png)

**Comment by ifsnop** [comment]
Could you please update with the line number where mysqldump-php runs out
of memory? I would like to try to fix it.

**Comment by ifsnop** [comment]
Seems that your version is not the latest, because line 524 is a comment. Could you try with latest version, or update your comment with the version (commit) you are using?

**Comment by douglasduartetb** [comment]
The version is "ifsnop/mysqldump-php": "^2.7"

**Comment by douglasduartetb** [comment]
For some reason, when i download with composer, the file isn't getting last version, so, i update manually, but, the error continuous on line 528
![Captura de Tela 2019-09-11 às 14 14 20](https://user-images.githubusercontent.com/7443043/64719639-10e76700-d49f-11e9-8e3d-cac5640770a9.png)

**Comment by douglasduartetb** [comment]
For now i resolve this problem increasing to 2Gb, but, sometimes, just 128Mb is not sufficiently, thats why i reported the error, tell me something, in your test, how many caracteres and columns has the tables?

**Comment by ifsnop** [comment]
Line 524, where you are getting the memory exhausted error, does:
~~~
array_push($this-tables, current($row); 
~~~
In this line we are storing the name of the table to be used later when exporting. So the only thing that matters is the number of characters of the table names.

In the tests I did, table name went from test1 to test49999.

~~~
CREATE TABLE `test1` (
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
~~~

What options of mysqldump-php are you using when calling start()?

**Comment by douglasduartetb** [comment]
I'm using this options:

````
'add-drop-table' => true
'extended-insert' => false
'exclude-tables' => array('/^(?![IGONRE]).*/')
// example: 'exclude-tables' => array('/^(?!test49).*/'), so everything that has test49 will be ignored
````

where [IGNORE], is a part of string that if has in name of the table, i'm ignoring.

**Comment by douglasduartetb** [comment]
So, after some updates, i dont need anymore to use **exclude-tables**, think this issue can be closed!

**Comment by smalos** [comment]
> So, after some updates, i dont need anymore to use **exclude-tables**, think this issue can be closed!

Do we need to keep this issue open?

**Comment by douglasduartetb** [comment]
For me, can close!
