### ISSUE TITLE
How to pass settings when using 'Plain old PHP'?

### ISSUE THREAD

**Issue by appel** [ifsnop/mysqldump-php#173]
Thank you for this excellent package! I would like to use mysqldump-php within a legacy code base. How do you pass settings when using 'Plain old PHP'? I tried it like this but couldn't get it to work (it does work without the settings array).

    include_once(dirname(__FILE__) . '/Ifsnop/Mysqldump/Mysqldump.php');
    $dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password', array('compress' => IMysqldump\Mysqldump::GZIP));
    $dump->start('storage/work/dump.sql');`

I'm using version 2.7.

**Comment by ifsnop** [comment]
Which version of PHP are you using? Could you paste the error message?

**Comment by appel** [comment]
Turns out I just made a dumb error, sorry! For those looking for the way to do it in legacy PHP:

    include_once(dirname(__FILE__) . '/Ifsnop/Mysqldump/Mysqldump.php');
    $dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password', array('compress' => Ifsnop\Mysqldump\Mysqldump::GZIP)); // or Mysqldump::BZIP2
    $dump->start('storage/work/dump.sql');`

Thanks, @ifsnop!
