### ISSUE TITLE
Is it possible to dump by chunks to bypass server timeouts?

### ISSUE THREAD

**Issue by codex-m** [ifsnop/mysqldump-php#174]
Hi, thanks for this MySQLdump-PHP library ! I have a question, is it possible to dump by chunks or parts to a a single SQL file? I'm implementing this via AJAX application something like this:

1. Client makes a server side request to dump db.( this is on my app or plugin)
2. PHP executes MySQLdump-PHP server side and writes to SQL file.(this is using the MySQLdump PHP library)
3. When its done the request is complete.

The downside to that workflow is when a server imposes a timeout say 60 seconds (which user cannot change either by php.ini or server settings like in shared hosting or forbidden by host). And it will take more than 60 seconds to completely dump the database (for example if database is quite large). Obviously this is not an issue if database is average size or small.

I'm reading the docs and I could not see if this is possible. Ideally I'm thinking that if we could dump to SQL file every 15 seconds (any seconds less than the timeout) and remembers it's last state. If 15 seconds has passed, the current request will end. Then it will make another request to invoke again MySQLdump PHP with its last remembered state to continue dumping until the database is fully dumped. 

Let me know if this is possible or if there is a workaround. Thanks!

**Comment by ifsnop** [comment]
I don't think this could be easy done without changing all the program logic.

Maybe you could use callbacks to update the state of the dump, and then check the state periodically in the ajax calls.

Regards,

**Comment by codex-m** [comment]
Ah ok thanks for the input. I'll check.

**Comment by aiso-net** [comment]
I would like this feature as well, to be able to get around PHP timeouts.
