### ISSUE TITLE
New release with functions dump feature

### ISSUE THREAD

**Issue by josteinAtProresult** [ifsnop/mysqldump-php#176]
Hi, this library looks really good. Thanks for working on it!

Could you please release a new version that includes the function dump feature from commit  https://github.com/ifsnop/mysqldump-php/commit/d8a8b20aa3ed3b49de13905459921188e4ee1aa0 ?

So that I can avoid depending on master.

**Comment by ifsnop** [comment]
Of course, just let me check #177

**Comment by ifsnop** [comment]
Done. See v2.8
