### ISSUE TITLE
Triggers not dumping

### ISSUE THREAD

**Issue by vleeuwenmenno** [ifsnop/mysqldump-php#177]
Triggers are being dropped when exporting with `'skip-triggers' => false` it doesn't seem to matter if it's true or false.

![image](https://user-images.githubusercontent.com/46482143/67671572-7e2f5880-f976-11e9-949e-61b8d8fb0155.png)

Code used to dump:

```php
    $dumpSet = array(
        'skip-triggers' => false
    );

    $tmpFile = tmpfile();
    $file = stream_get_meta_data($tmpFile)['uri'];

    include_once(dirname(__FILE__) . '/mysqldump/src/Ifsnop/Mysqldump/Mysqldump.php');
    $dump = new Ifsnop\Mysqldump\Mysqldump('mysql:host='.$_SESSION['config']['MySQL']['host'].';dbname='.$_SESSION['config']['MySQL']['dbname'], $_SESSION['config']['MySQL']['user'], $_SESSION['config']['MySQL']['pass'], $dumpSet);
    $dump->start($file);
```

**Comment by ifsnop** [comment]
Could you provide a simple test case? Integrated tests check that mysqldump-php is able to dump triggers when skip-triggers => false.

**Comment by vleeuwenmenno** [comment]
@ifsnop hmm I am using that code above to dump to a temp file. So what I am doing is I use your library to make rollbacks so I copy the database to a new database with a date in its name. But in phpMyAdmin I see that the triggers don't get copied over. Then when I download that temp file I see that create trigger is commented so it never makes them.

As I read in the documentation it should by default export the triggers. Yet it does not seem to do so for my case.

**Comment by ifsnop** [comment]
The create trigger is commented in order to avoid loading it to a mysql
version that doesn't support triggers.

That comment is mysql-version dependant. It will be loaded depending of the
version.

@ifsnop <https://github.com/ifsnop> hmm I am using that code above to dump
> to a temp file. So what I am doing is I use your library to make rollbacks
> so I copy the database to a new database with a date in its name. But in
> phpMyAdmin I see that the triggers don't get copied over. Then when I
> download that temp file I see that create trigger is commented so it never
> makes them.
>
> As I read in the documentation it should by default export the triggers.
> Yet it does not seem to do so for my case
>

**Comment by vleeuwenmenno** [comment]
Is there a way for me to export it without having it commented?

**Comment by vleeuwenmenno** [comment]
Alright so we have a server that has a web UI.
They can change values on there and remove/add.

If they make a mistake we want to be able to rollback the database to a day before it using this library it works very well except for it not copying over the triggers.

**Comment by ifsnop** [comment]
Please try importing the commented SQL, it will work. Mysql knows when to
ignore comments.

**Comment by ifsnop** [comment]
Dump is working correctly. Commented output is the recommended way for mysql to import depending on the server version.
