### ISSUE TITLE
Number of rows dumped

### ISSUE THREAD

**Issue by stevenbrookes** [ifsnop/mysqldump-php#179]
Hi

When I run a dump I'd like to know how many rows have been dumped overall or per table.  This is so I can discard any empty dump  files rather than add them to storage.  I can see that the listValues() function keeps a track of this to add it as a comment to the file.

What would be ideal would be for the total number of rows to be returned by the start() function.  Or perhaps even better an array of the table names and number of rows.  I can then make some decisions as to what I want to keep.

Are you interested in a pull request for something like this? 

Regards

Steve

**Comment by ifsnop** [comment]
Some stats returned from the call to the start function would be a very
good thing.

Other way to implement it is using the callbacks.

I will accept a PR, but take care not to impact performance.
