### ISSUE TITLE
How to set order of rows for setTableLimits, for dump only last rows?

### ISSUE THREAD

**Issue by MurzNN** [ifsnop/mysqldump-php#182]
At now library provide way to limit number of rows to dump via https://github.com/ifsnop/mysqldump-php#table-specific-export-conditions but via this, as I understand, we will dump only first XX rows?

Is there any way to set order of rows, for dump, for example, only last XX rows from table, or rows matching specific `where` condition?

**Comment by ifsnop** [comment]
You can use the 'where' key in the propertied array to limit dumped records.

Supporting limit as an array was proposed as a new feature and awaiting for someone with free time to implement it.

**Comment by MurzNN** [comment]
So, I can just use `where xxx limit 0,100`? Thanks!

**Comment by zfmaster** [comment]
> You can use the 'where' key in the propertied array to limit dumped records.
Somehow it sounds as a workaroundish workaround. What if in same time 'where' and 'setTableLimits' will be used?

> Supporting limit as an array was proposed as a new feature and awaiting for someone with free time to implement it.
I found only this #175 , but it's suggested to set offsets. On large tables it will produce performance issues and also you should reinvent bicycle if you don't know how much rows total you have. Let's continue discussion in #175

**Comment by MurzNN** [comment]
Ok, closing this in favor of #175
