### ISSUE TITLE
 Uncaught Error: Call to undefined method Ifsnop\Mysqldump\Mysqldump::setTransformTableRowHook() 

### ISSUE THREAD

**Issue by apurbajnu** [ifsnop/mysqldump-php#193]
Uncaught Error: Call to undefined method Ifsnop\Mysqldump\Mysqldump::setTransformTableRowHook() 
`use Ifsnop\Mysqldump as IMysqldump;
/**
 * Created by PhpStorm.
 * User: apurbapodder
 * Date: 3/17/20
 * Time: 12:28 PM
 */

class WP_SMART_DB_BACKUP {

    /**
     * $dump containt dump object
     */
    private $dump;

    public function __construct()
    {
        $this->dump = new IMysqldump\Mysqldump( 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASSWORD );
    
    }

    public function db_backup_create( $name = 'undefined.sql' ) {
        $this->proccess();
        $this->dump->start( $name );
    }

    private function proccess(){
        
        $this->dump->setTransformTableRowHook(function ($tableName, array $row) {
        
            error_log(print_r($tableName,1));
    
            return $row;
        }); 
        

    }
}`

**Comment by garas** [comment]
`setTransformTableRowHook()` method currently exists only in `master` branch, but not in latest `2.8` tag.

Install `master` branch with `composer require ifsnop/mysqldump-php:dev-master`.

@ifsnop Could you make new release?

**Comment by ifsnop** [comment]
Done!
