### ISSUE TITLE
Autocommit issue

### ISSUE THREAD

**Issue by christiandavilakoobin** [ifsnop/mysqldump-php#194]
If you perform a MySQL dump with the default parameters, it generates with the sentence "SET autocommit=0;". When you restore the database, this sentence changes the behaviour in that connection, which can have it enabled. I think that the autocommit parameter should be restored at the ending of the dump, or changing it to "START TRANSACTION", which closes after a COMMIT.

**Comment by ifsnop** [comment]
>
> Autocommit has the biggest success rate, and is the recommended way to
> import a dump from MySQL.
>

https://dev.mysql.com/doc/refman/8.0/en/optimizing-innodb-bulk-data-loading.html

But you are right, it should be saved and restored, although I don't
recommend sharing a connection to import a dump.

Would you like to provide a patch following MySQL recommendations?

Regards,

**Comment by christiandavilakoobin** [comment]
Hi,

Here you have the patch:
https://github.com/ifsnop/mysqldump-php/pull/195

Regards,

**Comment by christiandavilakoobin** [comment]
Hi again,

The travis CI failed, so I did a new PR and it worked now.

https://github.com/ifsnop/mysqldump-php/pull/196

Regards!
