### ISSUE TITLE
Can not run composer

### ISSUE THREAD

**Issue by mr-nit** [ifsnop/mysqldump-php#197]
Hi guys.
I am trying to run composer but it alerts:
`PS D:\xampp\composer> composer require ifsnop/mysqldump-php`
`Using version ^2.9 for ifsnop/mysqldump-php`
`Root package 'ifsnop/mysqldump-php' cannot require itself in its composer.json`
How to fix it?
Thank you!

**Comment by garas** [comment]
Are you running this from directory with `ifsnop/mysqldump-php` copy? You don't need `composer require` here.

You also get this error if you named your app as `ifsnop/mysqldump-php` in `composer.json`...

**Comment by mr-nit** [comment]
Hi Garas.
I copy only composer.json to D:\xampp\composer (where I installed composer).
After that I press Shift and right click -> Open PowerShell window here
And run composer
`composer require ifsnop/mysqldump-php`
Could you please show me what's something wrong?
Thank you!

**Comment by garas** [comment]
You are using Composer in wrong way:

1. You don't need to copy `composer.json` to use this package.
2. You need install packages in your application directory, not where installed composer.

If you starting fresh application, just execute `composer require ifsnop/mysqldump-php` and it will create `composer.json`.

Then create PHP file:
```php
<?php
require 'vendor/autoload.php';

use Ifsnop\Mysqldump\Mysqldump;

$dump = new Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password');
$dump->start('dump.sql');
```

**Comment by mr-nit** [comment]
> You are using Composer in wrong way:
> 
> 1. You don't need to copy `composer.json` to use this package.
> 2. You need install packages in your application directory, not where installed composer.
> 
> If you starting fresh application, just execute `composer require ifsnop/mysqldump-php` and it will create `composer.json`.
> 
> Then create PHP file:
> 
> ```
> <?php
> require 'vendor/autoload.php';
> 
> use Ifsnop\Mysqldump\Mysqldump;
> 
> $dump = new Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password');
> $dump->start('dump.sql');
> ```

It's ok now. 
Thank you so much Garas!
