### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by ve3** [ifsnop/mysqldump-php#198]
This code.
```
$dumpSettings = [
    'include-tables' => ['table1', 'table2'],
    'add-drop-table' => true,
];
$MysqlDump = new \Ifsnop\Mysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password', $dumpSettings, []);
$MysqlDump->start('file.sql');
```

Contain errors.

> Fatal error: Uncaught Error: Cannot use object of type stdClass as array inMysqldump.php on line 1891

**Comment by ifsnop** [comment]
Where does this code came from?

Looks like it is writen for php>7, and you are using it with php 5. Just replace "[1,2,3]" with "array(1,2,3)".
