### ISSUE TITLE
How to use compressing methods in this library.

### ISSUE THREAD

**Issue by kaustubh-scriptbite** [ifsnop/mysqldump-php#206]
I have tried it by passing array of dumpSetting array to constructor but no luck.

**Comment by smalos** [comment]
I'm using it like this:

```
$dumpSettings = [];
$dumpSettings['compress'] = Ifsnop\Mysqldump\Mysqldump::GZIP;
$dumper = new Ifsnop\Mysqldump\Mysqldump("mysql:host=$host_name;dbname=$db_name", 'user', 'password', $dumpSettings);
```

**Comment by kamihicouki** [comment]
> I have tried it by passing array of dumpSetting array to constructor but no luck.

Hi, Please take a look at my code.

[index.php · master · solutus / SALVAGE DB · GitLab](https://gitlab.com/solutus-llc/salvage-db/-/blob/master/index.php)
