### ISSUE TITLE
Latests commits not in release

### ISSUE THREAD

**Issue by christiandavilakoobin** [ifsnop/mysqldump-php#210]
If I install the package via composer, it downloads the last release, 2.9, but there ara some commits after that release which aren't in that package. Maybe the release should increments in a minor version each commit?

**Comment by ifsnop** [comment]
You are right. Last release was in April. I didn't make a new one because later commits made several changes that could break something. I usually give some months for any problem to arise before releasing. I will make a new release in the coming weeks.

**Comment by christiandavilakoobin** [comment]
Maybe it is an extra work, but it could be a medium version for potentially breaking changes, and minor version for bugfixes or some new flags, which shouldn't break anything. This way everyone can upgrade to the version they want.

Thank you for your reply!! 👍

**Comment by ifsnop** [comment]
Several releases have been made since Nov 2020, hope everyone is happy and nothing is broken.
