### ISSUE TITLE
How many tables it will export feedback

### ISSUE THREAD

**Issue by christiandavilakoobin** [ifsnop/mysqldump-php#212]
When dumping a database, I needed how many tables it will export in order to do a proper progressbar, so I added a new infoCallable call in exportTables method to know it.

This is the PR: https://github.com/ifsnop/mysqldump-php/pull/211

**Comment by mylemans** [comment]
Looks interesting, when will this be included?

**Comment by ifsnop** [comment]
Already implemented,  but issue was left open. Closing it now.
