### ISSUE TITLE
mysqldump-php error: Error getting procedure code, unknown output.

### ISSUE THREAD

**Issue by JosepBernad** [ifsnop/mysqldump-php#220]
First of all, thanks @ifsnop for this amazing library!

When I run the dump in the server (it totally fine on local) the backup is made properly but I keep getting this exception:
`mysqldump-php error: Error getting procedure code, unknown output. Please check 'https://bugs.mysql.com/bug.php?id=14564'`

This is my code:

```
try {
	$dumpSettings = array(
		'compress' => IMysqldump\Mysqldump::GZIP,
		'routines' => true,
	);
	$dump         = new IMysqldump\Mysqldump(
		'mysql:host=' . DB_HOST_IP . ';dbname=' . DB_NAME,
		DB_USER,
		DB_PWD,
		$dumpSettings
	);

	$dump->start($path . $fileName);

	$s3Client = new AwsS3Client();
	$s3Client->uploadBackupFile($year . $fileName);
} catch (\Exception $e) {
	echo 'mysqldump-php error: ' . $e->getMessage();
}
```

I looked for this error following the link and they talk about user privileges. The user I use if has granted all the privileges over the DB, so I don't know what could be the issue.

Thanks!

**Comment by garas** [comment]
What behavior do you expect: silently skip, warn, throw exception? What is the output of `mysqldump` when you dump same database with same permissions?

**Comment by JosepBernad** [comment]
When I run it locally, it creates the .sql.gzip and is sent to AWS S3 for storage. The problem is I can't create the .sql.gzip on the server (I have the same users and passwords) in both.

**Comment by JosepBernad** [comment]
Actually, I wasn't looking closely enough. The backup it's being made properly, but it rises the exception anyways. I'll edit the description of the issue to be more clear. Any ideas?

**Comment by ifsnop** [comment]
> Actually, I wasn't looking closely enough. The backup it's being made
> properly, but it rises the exception anyways. I'll edit the description of
> the issue to be more clear. Any ideas?
>

Hi, your user don't have rights to access the procedure table definition.

Check the documentation regarding what permissions are needed.

Kind regards,

>

**Comment by JosepBernad** [comment]
Thanks @ifsnop, I'll take a look on Monday!
