### ISSUE TITLE
Do not overwrite the dump file when it is not empty

### ISSUE THREAD

**Issue by mauriac** [ifsnop/mysqldump-php#222]
I would like to sequence the dumps, and for that I need to write to the same file. there is a way not to overwrite the contents of the file?

**Comment by ifsnop** [comment]
Use a temporary filename, and only rename it after dump, if no exceptions
were raised.

**Comment by mauriac** [comment]
Hello thank you for your answer, but please can you provide me some snippet that i can understand?

thank you.

**Comment by mauriac** [comment]
hello I found the solution,

we just have to replace in CompressNone::open function the write parameter of fopen in "a +" instead of "wb".

thank you for your help.

best regards
