### ISSUE TITLE
How to export certain tables from my database ?

### ISSUE THREAD

**Issue by quickIT77** [ifsnop/mysqldump-php#227]
Hello, I use this tool since recently and would like to know how I can export only certain tables with certain conditions. An example would be tab "a" from the database "Test" in the period from 2020 to 2021. Thanks for your help

**Comment by ifsnop** [comment]
There is an include_tables option that allows you to define the name of the
tables to dump. Regarding the period, if your table has a date field, you
could use the where option, to filter by date.

> Hello, I use this tool since recently and would like to know how I can
> export only certain tables with certain conditions. An example would be tab
> "a" from the database "Test" in the period from 2020 to 2021. Thanks for
> your help
>

**Comment by quickIT77** [comment]
Thanks for your quick reply. I would first like to briefly note that under latest version under Mysqldump.php under $dumpSettingsDefault 'if-not-exists' was not present in the array. I would need to add this Manuel based on the documentation. So at least in my case.Furthermore I would have a question about export dumpfile. Does this tool provide a way how to export dumpfile again ?

**Comment by ifsnop** [comment]
No option was removed regarding exporting dumpfile.
