### ISSUE TITLE
Unable to open dump file with GZIP compress

### ISSUE THREAD

**Issue by babeuloula** [ifsnop/mysqldump-php#237]
Hello,

When I tried to open a dump with GZIP compress I've got an error `Unable to open file. Maybe corrupted.`.
I've tried on Windows 10 (with WinRAR) and Ubuntu 20.04 (with default).

But on Ubuntu 20.04, if I try to extract with `right-click + extract here`, I've got a file named `data` without any extension.

There is my code : 

```php
$dump = new Mysqldump(
    'mysql:host=' . $this->database['host'] . ';dbname=' . $this->database['dbname'],
    $this->database['user'],
    $this->database['password'],
    [
        'compress' => Mysqldump::GZIP,
        'single-transaction' => true,
        'skip-dump-date' => true,
    ],
);

$dump->start($this->backupDir . "/" . static::DUMP_FILENAME); // dump.sql.tar.gz
```

Thanks for your help

**Comment by garas** [comment]
Try to rename to `dump.sql.gz` without `tar`. It now tries to open uncompressed `sql` as `tar` file so it is invalid `tar`.

**Comment by babeuloula** [comment]
Thanks, it's works better.
