### ISSUE TITLE
is there an option to split extended insert into specific number of rows?

### ISSUE THREAD

**Issue by pelister** [ifsnop/mysqldump-php#238]
do we have an option to split the insert statements with extended insert option which includes several VALUES lists. 

say we want to split 1000 rows of data into 4 INSERT with 250 VALUES list per INSERT

**Comment by garas** [comment]
You can use `extended-insert` and `net_buffer_length` options.

However it will limit INSERT statement max length, but not rows included in the statement as you wish.

**Comment by pelister** [comment]
> 
> 
> You can use `extended-insert` and `net_buffer_length` options.
> 
> However it will limit INSERT statement max length, but not rows included in the statement as you wish.

This is perfect, I can increase the net_buffer_length and run few tests to fix a value that will split the entire data into 200 VALUES list  per Insert. I checked the net_buffer_length and it is between Default Value - 16384 to Max Value 1048576. Thank You for pointing out this option.
