### ISSUE TITLE
skip-definer doesn't work for views with SQL SECURITY INVOKER

### ISSUE THREAD

**Issue by dweingart** [ifsnop/mysqldump-php#243]
The regex pattern defined in line 1904 (inside TypeAdapterMysql::create_view) fails if the view definition contains "SQL SECURITY INVOKER" instead of "SQL SECURITY DEFINER".

Changing the regex as follows fixes the bug:

**Line 1904 before:**

```php
.self::DEFINER_RE.'(?:\s+SQL SECURITY DEFINER|INVOKER)?)?\s+(VIEW .+)$/',
```

**Line 1904 after:**

```php
.self::DEFINER_RE.'(?:\s+SQL SECURITY (?:DEFINER|INVOKER))?)?\s+(VIEW .+)$/',
```

The `DEFINER|INVOKER` alternation needs to be in its own non-capturing group.

**Comment by amenk** [comment]
@dweingart Do you plan to create a PR?

**Comment by amenk** [comment]
Even with the Fix, we still see some definers (we are using smilesa/gdpr-dump)

```
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_abrechnung_letzter_monat` 
```

with skip-definer: true

This happens only for one view
