### ISSUE TITLE
Drump Procedures

### ISSUE THREAD

**Issue by brunoromeo001** [ifsnop/mysqldump-php#245]
Hello, it is with great and immense pleasure that I come to wish you my congratulations on the library.

I am exporting my database but the procedures are not being exported. Would I have to add some expersifica configuration to be exported?

**Comment by smalos** [comment]
By default,  routines  (procedures and functions) are not included when dumping a database. If you want to include the routines, you have to pass 

`'routines' => true`

in the $dumpSettings array.

**Comment by ifsnop** [comment]
The default parameters are the same as the ones found in mysqldump. I don't
think it will be a good idea to change them.

> By default, routines (procedures and functions) are not included when
> dumping a database. If you want to include the routines, you have to pass
>
> 'routines' => true
>
> in the $dumpSettings array
>

**Comment by smalos** [comment]
The default is set to false. How would you change it then?

**Comment by garas** [comment]
Use 5th parameter of constructor:

`$dumper = new IMysqldump\Mysqldump('mysql:host=localhost;dbname=testdb', 'username', 'password', [], ['routines' => true]);`

https://github.com/ifsnop/mysqldump-php#constructor-and-default-parameters
