### ISSUE TITLE
PHP 8.2 deprecate ${} string interpolation

### ISSUE THREAD

**Issue by heian-web** [ifsnop/mysqldump-php#247]
As per https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation
I noticed that this library extensively uses this syntax, which will effectively break it in PHP 9 (still a while before this happens) and may start to spam with deprecation notices quite soon. A simple and fast code refactoring should solve this.

**Comment by back-2-95** [comment]
This is taken care in https://github.com/druidfi/mysqldump-php fork. See #251

**Comment by faizanakram99** [comment]
> This is taken care in https://github.com/druidfi/mysqldump-php fork. See #251

I appreciate the effort made in forking and maintaining the repo, but as long as the author of this repo doesn't suggest any other fork as replacement or doesn't abandon this repo, I see no reason to "comment everywhere" here is the new fork, looks spammy to me tbh.

Replacing ${} with {$} is a small fix, doesn't need a full rewrite and I'm sure if a PR is made with just the fix @ifsnop will be kind to merge it (unless ofc it's decided to not support this repository)

**Comment by back-2-95** [comment]
We had business needs and we could not wait if some issues would be solved in a year or two's timespan. See activity on this repo (commits).

And ofc this was not only change/fix in our fork.

I cannot force anyone to recommend anything so I was just letting people know if they are still in the need.

**Comment by ifsnop** [comment]
Already merged. Thanks for the contribution.
