### ISSUE TITLE
Can we dump data without structures? 

### ISSUE THREAD

**Issue by sumonst21** [ifsnop/mysqldump-php#252]
Hello, 
I was wondering but not seeing the possiblity to dump data without the structures. 
havn't used it just looked into the Wiki & Readme. 

Help would be appricated. 

Thanks

**Comment by sumonst21** [comment]
Well, I've solved my issue with a solution from 2007 just by imporving that peace of code from mysql to mysqli. however it would be nice to have this feature with mysqldump-php. so letting this issue open to have a review by authors.

**Comment by garas** [comment]
Did you try `'no-create-info' => true`?

**Comment by sumonst21** [comment]
> Did you try `'no-create-info' => true`?

havn't @garas will give it a try and let you know. 
Thanks for the info. :)

**Comment by ifsnop** [comment]
The option "no-create-info" does exactly that..
