### ISSUE TITLE
Is it possible to get the output line by line

### ISSUE THREAD

**Issue by cyberpunkbln** [ifsnop/mysqldump-php#260]
Hello,
is it possible to get the output line by line?
In the moment store the output with output streaming into an variable:

```
ob_start();
$dump->start('php://output');
$dump = ob_get_contents();
ob_end_clean();
```

But i want to receive the output line by line, where i can alter the line and save money.
thx

**Comment by ifsnop** [comment]
Hi, output is already done line by line. Maybe you need to disable server buffering (https://stackoverflow.com/questions/6136783/output-line-by-line-with-php) , but from command line, you can test it by doing:

``
for i in `php t.php`; do echo "_M_${i}_M_"; done
``

and you will see al the lines surrounded by "_M_".

**Comment by cyberpunkbln** [comment]
@ifsnop thx, but can you short give an example how can i catch every output line? I mean when i disable server buffering and use $dump->start('php://output');??thx

**Comment by ifsnop** [comment]
Just a question, how do you know that you are not getting line by line
output?

> @ifsnop <https://github.com/ifsnop> thx, but can you short give an
> example how can i catch every output line? I mean when i disable server
> buffering and use $dump->start('php://output');??thx
>
