### ISSUE TITLE
Memory problem with large tables

### ISSUE THREAD

**Issue by adlcadn** [ifsnop/mysqldump-php#261]
I was using version 2.9 for a long time without any problems, but since the switch to version 2.10 several large tables (> 100,000 rows or 1 Gb) backups do not end sometimes with an indication of lack of memory: 
`Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/app/current/vendor/ifsnop/mysqldump-php/src/Ifsnop/Mysqldump/Mysqldump.php(1158)`
Sometimes with a crash without any error message. 
After multiple tests by trying to change for example the 'net_buffer_length' parameter without success, I went back to version 2.9 and everything is back in order. 
I invite you to look at this issue.

**Comment by ifsnop** [comment]
Thanks for your report,

Could you try to disable extended inserts?

I was using version 2.9 for a long time without any problems, but since the

**Comment by adlcadn** [comment]
Hello,

I had already tried this possibility and I just tested it again with 
`extended-insert' => false`
but without success: the process does not end and does not produce an error message.

**Comment by ifsnop** [comment]
When mergin #200, the use of MYSQL_ATTR_USE_BUFFERED_QUERY was dropped. So queries results were stored in memory, instead of being pulled row by row from database. I will upload a fix now.
