### ISSUE TITLE
Version 2.10 returning error 500 with large DB

### ISSUE THREAD

**Issue by shadowx-jb** [ifsnop/mysqldump-php#264]
After upgrading to version 2.10, after running the script and about 10 seconds later, the page returns error code 500. There is no error anywhere in the log files. I have a large database of about 1.5 GB (total records about 4.5 million in the database). I had to rollback to version 2.9 where it works fine. Where could the problem be? 

Version 2.10 works for me on localhost, but not on the server.

I have no problem with smaller databases on version 2.10

**Comment by ifsnop** [comment]
When mergin #200, the use of MYSQL_ATTR_USE_BUFFERED_QUERY was dropped. So queries results were stored in memory, instead of being pulled row by row from database. I will upload a fix now.
