### ISSUE TITLE
restore error - Mysql 8

### ISSUE THREAD

**Issue by silvasamu** [ifsnop/mysqldump-php#272]
Hello, 
I made the backup using this library and when restoring it gave me two errors:

**
The first is function. Please remove one ";"

Local:             
`"/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;;".PHP_EOL.
"/*!50003 SET sql_mode              = '".$sqlMode."' */ ;;".PHP_EOL.
"/*!50003 SET @saved_time_zone      = @@time_zone */ ;;".PHP_EOL.
"/*!50003 SET time_zone             = 'SYSTEM' */ ;;".PHP_EOL.`

**
The second is that the tables and columns are in double quotes "teste_table", the correct one is vim "`teste_table`"

Local: 

`        
$createTable = $row['Create Table'];
if ($this->dumpSettings['reset-auto-increment']) {
    $match = "/AUTO_INCREMENT=[0-9]+/s";
    $replace = "";
    $createTable = preg_replace($match, $replace, $createTable);
}}`

My best regards!!!

**Comment by ifsnop** [comment]
I can't get your results. could you provide some example code?
