### ISSUE TITLE
Not normalize line ending (CRLF, LF mixed in one export)

### ISSUE THREAD

**Issue by ve3** [ifsnop/mysqldump-php#281]
MySQLDump-PHP version 2.12

Export settings:
```php
$dumpSettings = [
    'include-tables' => $tables,
    'add-drop-table' => true,
    'default-character-set' => \Ifsnop\Mysqldump\Mysqldump::UTF8MB4,
    'routines' => true,
];
```

When I export with functions, or routines. It exports with line ending CRLF and LF mixed together.
Example:
```
DELIMITER ;;
CREATE DEFINER=`root`@`localhost` FUNCTION `udf_NaturalSortFormat`(`instring` varchar(4000), `numberLength` int, `sameOrderChars` char(50)) RETURNS varchar(4000) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    NO SQL
    DETERMINISTIC
    SQL SECURITY INVOKER
```
From the code above, the line `DELIMITER` end with `CRLF` but other lines in the functions or routines are end with `LF`.

I think it would be better if we normalize the line ending to be the same on all lines.

**Comment by ifsnop** [comment]
That code is created by the mysql server side, not by mysqldump-php. I see some danger trying to modify mysql generated code. This issue should be reported upstream as far as I understand.
