### ISSUE TITLE
utf8mb4 character problem

### ISSUE THREAD

**Issue by traBolic** [ifsnop/mysqldump-php#73]
I tried to dump this character properly but it allways return ? ? ? 
🎭
🎲
🐈
My friend, can show me hot to solve this problem?

My DB sql
http://tny.cz/a17994ec

**Comment by ifsnop** [comment]
Could you please create a dump with mysqldump, so i can reproduce the
problem?

**Comment by traBolic** [comment]
Of course http://tny.cz/d9db67e0

**Comment by ifsnop** [comment]
Thanks, but I was expecting to see the output from the original mysqldump
(the one that comes with mysql binaries). I imagine that maybe is not
possible, so I will try to reproduce the values. However, if you could
provide it, that would be great and reduce fix time.

**Comment by traBolic** [comment]
Ok this is the original mysqldump result http://tny.cz/b3b2ad7a

using with "mysqldump -u root bagislar2 > c:/mysql.sql"

**Comment by traBolic** [comment]
This is utf8mb4 original mysqldump
http://tny.cz/6f9d4477

"mysqldump --default-character-set=utf8mb4 -u root bagislar2 > c:/mysql.sql"

**Comment by traBolic** [comment]
Problem solved by deleting this line https://github.com/ifsnop/mysqldump-php/blob/master/src/Ifsnop/Mysqldump/Mysqldump.php#L181

First, I change this line to $this->dbHandler->exec("SET NAMES utf8mb4"); and it worked
after do that, i delete the line for good.

Also

I changed the https://github.com/ifsnop/mysqldump-php/blob/master/src/Ifsnop/Mysqldump/Mysqldump.php#L223

$this->compressManager->write($this->getDumpFileHeader());
to
$this->compressManager->write(chr(239).chr(187).chr(191) .$this->getDumpFileHeader());

However i cant create sql file without bom signature but it worked so far(i believe)

And I know, this is not a global solution :)

**Comment by ifsnop** [comment]
I have added a new option to the dumpSettings array. You could now specify character encoding when connecting, just like mysql/mysqldump does with "default-character-set". When using "utf8mb4", there will be support for the four byte utf8 character encoding.

There is a new test that ensures that utf8mb4 columns are correctly dumped.

Please test this fix, as it could depend in configuration settings from my.cnf (it tries not to do so)

pd.- Until mysql sets the default connection mode to utf8mb4, mysqldump-php will use utf8.

**Comment by ifsnop** [comment]
I prefer not to add the BOM signature since it is not needed for utf8 file reading, and won't fix the issue with database dumps.
