### ISSUE TITLE
CompressManagerFactory::open should not append file extension if compression enabled

### ISSUE THREAD

**Issue by gwarnants** [ifsnop/mysqldump-php#75]
Currently, CompressManagerFactory::open() append a file extension to the written dump depending on the enabled compression method (".gz" if GZIP, ".bz2" if BZIP2). I think users should decide the real output filename they want. This will solve many problems to deduct the output filename if internal classes didn't change the filename anymore.

```php
$settings = array(
    'compress' => Mysqldump::GZIP
);
$dump = new Mysqldump($db, $username, $password, $host, $type, $settings);

// currently :
$dump->start('dump.sql'); // write dump.sql.gz

// should become :
$dump->start('dump.sql.gz'); // write dump.sql.gz

```

**Comment by ifsnop** [comment]
I think that you are right. Could you provide a PR that removes the extension appending and the getfilename methods recently added? Filename provided by user is the only one that should be used.

**Comment by gwarnants** [comment]
I agree, things will be easier. See my last commits

**Comment by ifsnop** [comment]
Merged.
