### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) 

### ISSUE THREAD

**Issue by iqbalmalik89** [ifsnop/mysqldump-php#81]
Hello,

I am facing this error on remote server.

 SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s)

**Comment by ifsnop** [comment]
Could you paste your calling parameters ?

**Comment by iqbalmalik89** [comment]
Here is my code. I am using Lumen.

		try {
		    $dump = new IMysqldump\Mysqldump(env('DB_DATABASE'), env('DB_USERNAME'), env('DB_PASSWORD'));
		    $dump->start(\Utility::getRoot('backup').$backupFile);
		} catch (\Exception $e) {
		    echo 'mysqldump-php error: ' . $e->getMessage();
			return false;
		}

**Comment by ifsnop** [comment]
Please update mysqldump-php to the latest version. A fix was pushed a year
ago that changed GLOBAL to SESSION, which doesn't requiere SUPER privilege.
