### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pdewouters** [ifsnop/mysqldump-php#83]
Hi,

 I just spent a while trying to figure out an error related to privileges, then I noticed it has been fixed :)
Are you planning a new release soon?

thanks

**Comment by ifsnop** [comment]
Hi there!

Great that it has been fixed! 

Except from adding support for #77 and #61, I don't have more updates planned, for the only reason that now mysqldump-php has reached maturity, and nothing more is needed. Of course, PR are welcomed, and the same goes for suggestions!

Regards,

**Comment by pdewouters** [comment]
hi @ifsnop - sorry if I was unclear. What I meant was the latest tag `1.5` is behind master by a few commits, one of which fixes the need to have SUPER privileges. Are you going to tag a new version so I can update via composer?

**Comment by ifsnop** [comment]
Done, v1.6 is out :smile:

**Comment by pdewouters** [comment]
:+1:
