### ISSUE TITLE
Table was not locked with LOCK TABLES 

### ISSUE THREAD

**Issue by neitanod** [ifsnop/mysqldump-php#87]
When trying to restore a dump I get the error message:

Error
SQL query: DocumentationEdit Edit

SELECT `comment` 
FROM `phpmyadmin`.`pma_column_info` 
WHERE db_name = 'test'
AND table_name = ''
AND column_name = '(db_comment)'

MySQL said: Documentation

#1100 - Table 'pma_column_info' was not locked with LOCK TABLES 

I tried both "lock-tables" true and the default (false, according to the documentation)

**Comment by ifsnop** [comment]
Sql you pasted is not part of the dump. Could you please paste a small
dump? How did you tried the import? From command line?
