### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by basz** [ifsnop/mysqldump-php#91]
Hi

i've been experimenting with your library for a bit. I found that while you can write to 'php://sndout' stream you by giving that string as argument it is not possible to provide your own resource.

```
$handle = fopen('php://temp', 'w+');

$dumper->start($handle);

/* $filesystem is a virtual filesystem, from https://github.com/thephpleague/flysystem */
$filesystem->writeStream($path, $handle);
fclose($handle);
```

I'v been able to do this for the uncompressed version by modifying the compression class a bit. (basically test if resource then use it and don't close it). However the compressed version need to do gzopen or bzopen so that won't be that easy.

Unfortunately I am not very good at resource handling. I just don't see how to do this - though i think it must be possible with custom stream wrappers. I'm hoping you see a feature like this would be useful and see a way to implement this into a future version... 

Thanks!

**Comment by ifsnop** [comment]
If I understood correctly, for example, with streams support (and
flysystem) you could store directly a backup to s3. Am I right? Is this
what you are looking for?

**Comment by basz** [comment]
Precisely that's the idea. For large dumps...

> Op 30 sep. 2015 om 08:43 heeft diego torres <notifications@github.com> het volgende geschreven:
> 
> If I understood correctly, for example, with streams support (and
> flysystem) you could store directly a backup to s3. Am I right? Is this
> what you are looking for?

**Comment by mbmleone** [comment]
Maybe this is an alternative:
http://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html
I have tried it and it works with mysqldump-php.
