### ISSUE TITLE
only all database schema with routines, event, procedures, function

### ISSUE THREAD

**Issue by phoniq** [ifsnop/mysqldump-php#92]
I want dump all database schema with all objects (routines, event, procedures, function). Mysqldump-php dump database schema without this object.

**Comment by ifsnop** [comment]
Sorry, I don't understand "Only all database schema with all objects". That
should be the default behaviour. Could you provide some example?

On Thu, Oct 1, 2015 at 9:39 AM, phoniq <notifications@github.com> wrote:

> I want dump all database schema with all objects (routines, event,
> procedures, function). Mysqldump-php dump database schema without this
> object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/92>.
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain

**Comment by phoniq** [comment]
sorry, my english is bad.
i wont dump all table, routines, event, procedures, function ....... but mysqldump-php not dump event, procedures, function

**Comment by megakraken** [comment]
I think what phoniq is saying is that mysqldump-php currently will not export stored procedures, which I think would be a really useful addition.

**Comment by ifsnop** [comment]
This commit will dump procedures. Since I myself don't use procedures, I would like some testing from @phoniq (or anyone) before dumping the rest.
