### ISSUE TITLE
add option for complete-insert

### ISSUE THREAD

**Issue by jmserra** [ifsnop/mysqldump-php#93]
please add an option for --complete-insert, that would be tremendously helpful!

thanks

https://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_complete-insert

**Comment by ifsnop** [comment]
Did you tried setting "extended-insert
<https://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_extended-insert>,"
to false? Maybe this will solve the problem for you.

Regards,

On Fri, Oct 2, 2015 at 12:19 PM, Josep Ma. <notifications@github.com> wrote:

> please add an option for --complete-insert, that would be tremendously
> helpful!
>
> thanks
>
>
> https://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_complete-insert
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/93>.
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain

**Comment by jmserra** [comment]
Hi Thanks, didn't tried that but i'm guessing would have worse performance, as i would still like to get multiple values in the same query (so imports are much quicker for thousands of rows) but at the same time to specify the columns, thats why i though the --complete-insert would be ideal

thanks

**Comment by ifsnop** [comment]
Could you provide some example of the complete-output option?

**Comment by jmserra** [comment]
Thanks a lot! really appreciate your development :)
