### ISSUE TITLE
Pass to constructor PDO object instead of string

### ISSUE THREAD

**Issue by ymakux** [ifsnop/mysqldump-php#96]
Hello
Isn't be better to pass initialized PDO object instead of "'mysql:host=localhost;dbname=testdb', 'username', 'password'" arguments? Many people have PDO already set (CMS etc)

**Comment by ifsnop** [comment]
IMHO, is better to create a new connection for mysqldump-php. When
mysqldump-php creates it, it configures the session, and doesn't need to be
aware of other rare conditions that where changed by the CMS.  Also, it is
better to have privilege separation, and permissions for mysqldump-php
should be different from the ones needed to the CMS. When running
mysqldump-php, connection could be blocked for a long period of time. If
the CMS tries to execute any action on the db, it will also be locked if
they are sharing the same connection.

Regards,

On Mon, Nov 2, 2015 at 1:35 AM, ymakux <notifications@github.com> wrote:

> Hello
> Isn't be better to pass initialized PDO object instead of
> "'mysql:host=localhost;dbname=testdb', 'username', 'password'" arguments?
> Many people have PDO already set (CMS etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/96>.
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain

**Comment by ymakux** [comment]
Ok, thanks for explanation
