### ISSUE TITLE
include-tables bug

### ISSUE THREAD

**Issue by adamslovacek** [ifsnop/mysqldump-php#97]
method getDatabaseStructure():
-consider non empty include-tables. 
-foreach removes all the records from $this->dumpSettings['include-tables'] ( unset($this->dumpSettings['include-tables'][$elem]);)
$this->dumpSettings['include-tables'] is now empty resulting dump all the views.

also the set of triigers should respect the set of exported tables - create all the triggers for exported tables and no one for omnited tables

Best regards Adam

**Comment by ifsnop** [comment]
Please check a proposed fix at https://github.com/ifsnop/mysqldump-php/commit/a906a96bf40858221c5f66a252af976053fb1a64

**Comment by adamslovacek** [comment]
Well, I'm not sure this is the right solution. At least to reflect mysqldump behaviour. 
It actually in this case considers views as tables, so any view included in include-tables is dumped.
As mentioned in previous post, the triggers should also reflect the set of tables beeing exported -  dump **all the triggers** for all tables **beeing dumped** and dump **no triggers** for tables that are **not dumped**.

**Comment by ifsnop** [comment]
Just to clarify: If I have two tables, named "a" and "b", and a view that
joins the two tables, what should mysqldump dump if only "a" is selected in
include-tables?

**Comment by adamslovacek** [comment]
Only "a"... But if you have include-tables a b viewname , it should dump
table "a","b" and view "viewname"

mysqldump takes the view "viewname" as it was a table (include-tables) and
dumps it too.

Best regards
Adam

2015-11-09 9:46 GMT+01:00 diego torres <notifications@github.com>:

> Just to clarify: If I have two tables, named "a" and "b", and a view that
> joins the two tables, what should mysqldump dump if only "a" is selected in
> include-tables?
> El 09/11/2015 09:20, "Adam Slováček" <notifications@github.com> escribió:
>
> > Well, I'm not sure this is the right solution. At least to reflect
> > mysqldump behaviour.
> > It actually in this case considers views as tables, so any view included
> > in include-tables is dumped.
> > As mentioned in previous post, the triggers should also reflect the set
> of
> > tables beeing exported - dump *all the triggers* for all tables *beeing
> > dumped* and dump *no triggers* for tables that are *not dumped*.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ifsnop/mysqldump-php/issues/97#issuecomment-154994528>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifsnop/mysqldump-php/issues/97#issuecomment-154998306>
> .
>



-- 

S pozdravem
Adam Slovacek
adamslovacek@gmail.com

**Comment by ifsnop** [comment]
I think I got it down in https://github.com/ifsnop/mysqldump-php/commit/ab45f0201b8dbd612edf464304174954590d3dc8
